### ISSUE TITLE
Can't build, too old kotlin

### ISSUE THREAD

**Issue by JakubNeukirch** [operando/advertising_id#1]
I am getting gradle error due to too old kotlin in advertising_id 'The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'advertising_id' is using version 1.2.31.'

**Comment by soofi-cheenilabs** [comment]
getting the same error. Please let me know if there's a working plugin to get Advertising ID.

Thanks!

**Comment by JakubNeukirch** [comment]
@soofi-chenilabs just change kotlin version in gradle of advertising_id lib

**Comment by soofi-cheenilabs** [comment]
I can't locate where the file is. Can you please send me the complete directory? It will be helpful.

Thanks!

**Comment by soofi-cheenilabs** [comment]
> @soofi-chenilabs just change kotlin version in gradle of advertising_id lib

thanks man!
