### ISSUE TITLE
Plugin called in background mode crashing on Android

### ISSUE THREAD

**Issue by jocelyngriselle** [operando/advertising_id#16]
Hello and thank you for your plugin!

I'm having an issue when calling `AdvertisingId.id(true)` on Android when running in the background. It leads to the late variable `activity` being not initialized thus crashing with `kotlin.UninitializedPropertyAccessException` error.

I wonder if you would accept a Merge Request dealing with this ? I was thinking of something like below :
```
if (activity.isInitialized) {
     val id = AdvertisingIdClient.getAdvertisingIdInfo(activity).id
     activity.runOnUiThread {
           result.success(id)
      }
 }
 else {
      result.error("", "Activity not initialized", null)
 }
```

What do you think ?
Best regards

**Comment by operando** [comment]
Thank you for bug reporting!
I will accept this fix.
https://github.com/operando/advertising_id/pull/17
