### ISSUE TITLE
maybe a bug: `isLimitAdTrackingEnabled` has different meaning for android and iOS 

### ISSUE THREAD

**Issue by beeth0ven** [operando/advertising_id#19]
Hi, thank you for providing this useful tool!

I may found a bug for our api:

`AdvertisingId.isLimitAdTrackingEnabled`: https://pub.dev/documentation/advertising_id/latest/advertising_id/AdvertisingId/isLimitAdTrackingEnabled.html

`isLimitAdTrackingEnabled` means whether ad track is **disabled**(limited), here is the explaination: https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info#isLimitAdTrackingEnabled()

From what I see, the implementation for iOS explain `isLimitAdTrackingEnabled` as whether ad track is **enable**:
https://github.com/operando/advertising_id/blob/master/ios/Classes/SwiftAdvertisingIdPlugin.swift#L41-L45

So i guess`isLimitAdTrackingEnabled` have different meaing for android and iOS:
- android: ad track **disabled**
- iOS: ad track **enabled**

I guess iOS implementation is not correct. What do you thing about this?

Thank you!

**Comment by operando** [comment]
@beeth0ven 
Thank you for bug reporting!
As you pointed out, I think the iOS implementation is not correct.

Created a Pull Request that fixed the bug.
https://github.com/operando/advertising_id/pull/22/files
Is this fix okay?

**Comment by beeth0ven** [comment]
@operando 

Yes, I think this implementation is okay:
https://github.com/operando/advertising_id/pull/22/files

Thank you for the update!

**Comment by operando** [comment]
released 2.1.1 with the bug fixed.
Thank you 👍

**Comment by beeth0ven** [comment]
Thank you!

You are a lifesaver!
