### ISSUE TITLE
Plugin not working. Is it even undermaintaince?

### ISSUE THREAD

**Issue by yashwp** [operando/advertising_id#25]
I have installed the package into a separate repository. And as soon I pressed the button to call the function `await AdvertisingId.id(true);` I'm getting below error:

```
MissingPluginException(No implementation found for method getAdvertisingId on channel advertising_id)
```

Flutter - `v2.5.1`

**Comment by operando** [comment]
@yashwp 
Thanks for the issue.

This plugin is already supported by the new plugin APIs.
Please check the following document and redo the package setup.
https://docs.flutter.dev/development/packages-and-plugins/plugin-api-migration
