### ISSUE TITLE
Build fails on compilation process. 

### ISSUE THREAD

**Issue by AshereLoker** [operando/advertising_id#28]
Hi. Issue from 2.2.0 package's version. After update Kotlin to `1.6.10` gotcha this error (pasted down here). Gradle version is 7.1.1. 
`flutter clean`, and repeated `flutter pub get` don't work. Tried to downgrade Kotlin and package version, but it's not work at all. 
Cleaning `Cache` from `user/AppData/Local/pub` and `flutter/bin` not working too.

Also, try to build apk from `example`, same story.

```
e: C:\Users\Ashere\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\advertising_id-2.2.0\android\src\main\kotlin\com\os\operando\advertisingid\AdvertisingIdPlugin.kt: (24, 31): **Type mismatch: inferred type is Activity? but Activity was expected**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':advertising_id:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```
![Issue screen](https://user-images.githubusercontent.com/74857291/166668771-63e734d5-922f-44a5-b5de-8da47f885c11.png)

**Comment by sergey-tarasenko-idf** [comment]
Hi, we also encountered this problem. Any news?

**Comment by operando** [comment]
Thanks for the issue.
Upgrading to version 2.3.0 can solve this problem.
