### ISSUE TITLE
Type mismatch: inferred type is Activity? but Activity was expected

### ISSUE THREAD

**Issue by agmyryak** [operando/advertising_id#29]
After updating to flutter 3 I have got:
.pub-cache/hosted/pub.dartlang.org/advertising_id-2.2.0/android/src/main/kotlin/com/os/operando/advertisingid/AdvertisingIdPlugin.kt: (24, 31): Type mismatch: inferred type is Activity? but Activity was expected

**Comment by kmh339** [comment]
I solved it temporarily.
Under the 
/advertising_id-2.2.0/android/src/main/kotlin/com/os/operando/advertisingid/AdvertisingIdPlugin.kt
```
companion object {
       @JvmStatic
        fun registerWith(registrar: Registrar) {
            val channel = MethodChannel(registrar.messenger(), "advertising_id")
            val plugin = AdvertisingIdPlugin()
            plugin.activity = registrar.activity()!!
            channel.setMethodCallHandler(plugin)
        }
    }
```

Try `plugin.activity = registrar.activity()!!`

**Comment by operando** [comment]
Thanks for the issue.
Upgrading to version 2.3.0 can solve this problem.
