### ISSUE TITLE
Multiple commands produce error when archiving with v2.7 (ios)

### ISSUE THREAD

**Issue by jihuncha** [operando/advertising_id#52]
Hello,

I'm encountering an issue when archiving my project using v2.7 and later versions. The error message I'm receiving is "Multiple commands produce". As a temporary workaround, I've reverted to using v2.6.

The problem seems to occur when using this plugin in conjunction with https://github.com/deniza/app_tracking_transparency. I'm unsure if the issue lies with the app_tracking_transparency plugin, so I'm creating this issue to seek clarification and potential solutions.

It appears that the commit in this pull request might be the cause of the conflict:
https://github.com/operando/advertising_id/pull/51

However, as I'm not deeply familiar with iOS development, I'd appreciate your insights on this matter.

Here's the specific error message I'm receiving: 
`Multiple commands produce '/user/Library/Developer/Xcode/DerivedData/Runner***grufmaccwxlhiicanhariomaaftt/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/app_tracking_transparency_privacy.bundle'`

Could you please advise on how to resolve this issue or provide any information on whether this is a known problem with the app_tracking_transparency plugin?

Thank you for your assistance.

**Comment by operando** [comment]
@jihuncha 
Thanks for the issue.
Upgrading to version 2.7.1 can solve this problem.
