### ISSUE TITLE
Error launching application on iOS 13.6

### ISSUE THREAD

**Issue by hczmail** [operando/advertising_id#54]
Xcode build done.                                           132.2s
Installing and launching...
(lldb) dyld: dependent dylib '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' not found for '/private/var/containers/Bundle/Application/28FCB71D-B7BD-47EB-B0E4-E1C93C66E653/Runner.app/Frameworks/advertising_id.framework/advertising_id', tried but didn't find: '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' 
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001037f4d90 dyld`__abort_with_payload + 8
dyld`:
->  0x1037f4d90 <+8>:  b.lo   0x1037f4dac               ; <+36>
    0x1037f4d94 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1037f4d98 <+16>: mov    x29, sp
    0x1037f4d9c <+20>: bl     0x1037f329c               ; cerror_nocancel
Target 0: (Runner) stopped.
Error launching application on Xr.

**Comment by operando** [comment]
@hczmail 
Thanks,Issue.

AppTrackingTransparency is a Framework added in iOS 14.
Therefore, if you build on iOS 13.6, you will likely need to adjust the Framework link settings.
Since the framework linking setting issue is not a library issue, the issue will be closed.
